networks:
  default:
    external:
      name: roboshop
volumes:
  mongodb: #docker volume create mongodb
  # redis:
  # mysql:
  # rabbitmq:
services:
  # docker run -d --name mongodb--network=roboshop mongodb:1
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    volumes:
    - source: mongodb
      target: /data/db
      type: volume

  catalogue:
    image: catalogue:v1
    depends_on:
      - mongodb